// swift-tools-version:6.0
import PackageDescription

// PherryKit — the Pherry wire re-implemented as a Swift package.
//
// This is the *second* implementation of the frozen TypeScript wire (`@pherry/channel`,
// `@pherry/relay-core`, `@pherry/protocol`, `@pherry/sdk`): the E2EE secure channel, the
// blind-relay outer protocol, the RPC + PTY frame codecs, and the control-plane HTTP client
// the iOS controller speaks. It is proven byte-for-byte equivalent to the reference by the
// conformance vectors under `Tests/PherryKitTests/Vectors/` (regenerated by
// `ios/scripts/generate-vectors.mjs` from the built TS dists — never guessed).
//
// No external dependencies: CryptoKit + Foundation + Network only. Builds and tests under
// Swift 6 strict concurrency.
let package = Package(
    name: "PherryKit",
    platforms: [
        .iOS(.v17),
        .macOS(.v14),
    ],
    products: [
        .library(name: "PherryKit", targets: ["PherryKit"]),
    ],
    targets: [
        .target(
            name: "PherryKit"
        ),
        .testTarget(
            name: "PherryKitTests",
            dependencies: ["PherryKit"],
            resources: [
                .copy("Vectors"),
            ]
        ),
    ]
)
