packages:
  - protocol
  - packages/*
  - apps/*
onlyBuiltDependencies:
  - '@biomejs/biome'
  - esbuild
  - node-pty
allowBuilds:
  '@biomejs/biome': true
  '@clerk/shared': false
  esbuild: true
  node-pty: true
