/**
 * The POSIX-`sh` PATH shim template — the body `pherry board` writes to
 * `~/.pherry/shims/<agent>` for every known agent.
 *
 * When the user types `gemini` in a boarded repo, this script (found first on
 * `PATH`) runs in place of the real binary and decides, through a **fail-open
 * ladder**, whether to hand the launch to the host daemon (`pherry open`) or to
 * exec the real agent bare. "Fail open" is the rule at every rung: the moment
 * anything is off — the recursion guard is set, there is no TTY, a passthrough
 * flag is present, the cwd is not under a boarded repo, the repo is anchored, or
 * the real binary cannot be found — the script execs the real agent with the
 * original args, so a launch can never break.
 *
 * The rendered script is strictly POSIX (works under macOS `/bin/sh` and dash),
 * filters `PATH` with no external tools, and is regenerated on every `board`.
 */

/** Options for {@link renderShimScript}. */
export interface ShimScriptOptions {
  /** The agent id this shim stands in for, e.g. `'gemini'`. */
  agent: string
  /**
   * The command that runs the Pherry CLI, baked **verbatim** into the custody
   * exec line. Defaults to `'pherry'`. Board-controlled, trusted text; it may be
   * several words (e.g. `'/usr/bin/node' '/opt/pherry.js'`), which is why it is
   * emitted unquoted.
   */
  pherryCommand?: string
}

/**
 * Render the complete shim script for `agent`. Pure: the same options in yield
 * the same bytes out. The result is a self-contained `sh` script — shebang,
 * generated-file header, and the fail-open ladder — ready to write and `chmod`.
 */
export function renderShimScript(options: ShimScriptOptions): string {
  const { agent } = options
  const pherryCommand = options.pherryCommand ?? 'pherry'
  return `#!/bin/sh
# Generated by pherry board — overwritten on every board; do not edit by hand.
# Fail-open PATH shim for "${agent}": an interactive launch inside a boarded,
# un-anchored repo is handed to the host daemon; anything else execs the real
# "${agent}" unchanged, so a launch can never break.

pherry_home="\${PHERRY_HOME:-$HOME/.pherry}"
shim_dir="$pherry_home/shims"

# Rebuild PATH without our own shim dir, in pure sh, so we can find the real bin.
real_path=""
saved_ifs="$IFS"
IFS=":"
for dir in $PATH; do
  [ "$dir" = "$shim_dir" ] && continue
  if [ -n "$real_path" ]; then
    real_path="$real_path:$dir"
  else
    real_path="$dir"
  fi
done
IFS="$saved_ifs"

# Fall open: exec the real "${agent}" from the cleaned PATH, or fail loudly.
run_free() {
  real_bin=$(PATH="$real_path" command -v "${agent}") || real_bin=""
  if [ -z "$real_bin" ]; then
    echo "pherry: ${agent} not found on PATH" >&2
    exit 127
  fi
  exec "$real_bin" "$@"
}

# Recursion guard: already inside a custody session.
[ -n "\${PHERRY_LOCAL_ID:-}" ] && run_free "$@"

# Not an interactive terminal (PHERRY_SHIM_ASSUME_TTY is a test-only override).
if [ -z "\${PHERRY_SHIM_ASSUME_TTY:-}" ]; then
  if [ ! -t 0 ] || [ ! -t 1 ]; then
    run_free "$@"
  fi
fi

# A passthrough / non-interactive flag anywhere in the args.
for arg in "$@"; do
  case "$arg" in
    --help | -h | --version | -V | -v | --print | -p) run_free "$@" ;;
  esac
done

# The physical cwd is not at or under a boarded repo.
boarded="$pherry_home/boarded.list"
[ -f "$boarded" ] || run_free "$@"
cwd=$(pwd -P)
matched=""
while IFS= read -r line || [ -n "$line" ]; do
  [ -z "$line" ] && continue
  case "$cwd/" in
    "$line"/*)
      matched="$line"
      break
      ;;
  esac
done < "$boarded"
[ -z "$matched" ] && run_free "$@"

# The matched repo is anchored (the soft brake): pass launches through.
anchored="$pherry_home/anchored.list"
if [ -f "$anchored" ] && grep -qFx "$matched" "$anchored"; then
  run_free "$@"
fi

# Custody: resolve the real bin as the fail-open fallback, then hand to the host.
real_bin=$(PATH="$real_path" command -v "${agent}") || real_bin=""
[ -z "$real_bin" ] && run_free "$@"
exec ${pherryCommand} open "${agent}" --exec-fallback "$real_bin" -- "$@"
`
}
